### ISSUE TITLE
 大佬我倒是想联系您，请问目前还能用吗2020.02.23 祝大佬早日遇到白富美 回答下我

### ISSUE THREAD

**Issue by sw586** [Hana-ame/cloudflare-ddns-python#1]
大佬我倒是想联系您，请问目前还能用吗2020.02.23 祝大佬早日遇到白富美 回答下我

**Comment by sw586** [comment]
CF接口好像更新了，您更新下吧就算只有我两用也是一种快乐啊

**Comment by Hana-ame** [comment]
@sw586 我试下来接口还是能用的，考虑一下是不是哪里填错了
一个json的示例
`{"name": "www", "Authorization": "Bearer 8CP**********************************qUV", "Zone": "7b8**************************c57", "recordID": "0d7**************************218", "isSetedID": false, "sleeptime": 20}`
