### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by MoYu-YYDS666** [Hana-ame/cloudflare-ddns-python#2]
建议在arg处增加 [TTL] 可选项，来控制DNS的存活时间

**Comment by Hana-ame** [comment]
See: https://github.com/Hana-ame/cloudflare-ddns-python/tree/feature/ttl

usage:
```
py .\example.py  example.domain f5a5e86ea16a1ab312f43a9624ed7060 72UYxeU3dgxGnXPjRxCwIckkwGcHUQQtIHkT06cN 60 4

Mode: IPv4
ZONE_ID: f5a5e86ea16a1ab312f43a9624ed7060
TOKEN: 72UYxeU3dgxGnXPjRxCwIckkwGcHUQQtIHkT06cN
Domain: example.domain
TTL: 60
```
any argument larger than 10 and is a number will be recognized as a parameter for TTL. (4 or 6 will be recognized as IPv4 or IPv6.)

although automatic mode works well for almost all cases.

https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-patch-dns-record
> Time To Live (TTL) of the DNS record in seconds. Setting to 1 means 'automatic'. Value must be between 60 and 86400, with the minimum reduced to 30 for Enterprise zones.
